"use client";

/**
 * Save generated bytes through the Electron fs bridge (saveDialog + writeFile)
 * with a browser blob-download fallback. ONE implementation shared by every
 * feature that exports a document — never `<a download>` directly in Electron.
 */

import { hasElectronFS, saveFileDialog, writeLocalFile } from "@/platform/electron/electron-fs";
import type { ExportKind } from "@/workers/export-types";

const MIME: Record<ExportKind, string> = {
  pdf: "application/pdf",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
};

const EXT_FILTERS: Record<ExportKind, { name: string; extensions: string[] }> = {
  pdf: { name: "PDF Document", extensions: ["pdf"] },
  xlsx: { name: "Excel Workbook", extensions: ["xlsx"] },
  docx: { name: "Word Document", extensions: ["docx"] },
  pptx: { name: "PowerPoint Presentation", extensions: ["pptx"] },
};

export interface SaveResult {
  saved: boolean;
  path?: string;
}

export async function saveBytes(
  bytes: ArrayBuffer,
  fileName: string,
  kind: ExportKind,
): Promise<SaveResult> {
  if (hasElectronFS()) {
    const filePath = await saveFileDialog({
      defaultPath: fileName,
      filters: [EXT_FILTERS[kind]],
    });
    if (!filePath) return { saved: false };
    await writeLocalFile(filePath, bytes);
    return { saved: true, path: filePath };
  }

  // Browser fallback.
  const url = URL.createObjectURL(new Blob([bytes], { type: MIME[kind] }));
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
  return { saved: true };
}
