blockExoticSubdeps: true

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - '@bitdisaster/exe-icon-extractor'
  - '@swc/core'
  - '@vaadin/vaadin-usage-statistics'
  - autoevals
  - better-sqlite3
  - better-sqlite3-multiple-ciphers
  - core-js
  - core-js-pure
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - lefthook
  - msgpackr-extract
  - msw
  - node-llama-cpp
  - onnxruntime-node
  - protobufjs
  - sharp
  - unrs-resolver
