blockExoticSubdeps: false

onlyBuiltDependencies:
  - '@bitdisaster/exe-icon-extractor'
  - '@swc/core'
  - better-sqlite3
  - core-js
  - core-js-pure
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - lefthook
  - msw
  - onnxruntime-node
  - protobufjs
  - sharp
  - unrs-resolver
