/**
 * Static help-center content (features, FAQ, keyboard shortcuts).
 *
 * Kept as a plain, dependency-light data module (no `"use client"`) so the
 * copy can be indexed once for fuzzy search and reused by the screen, the
 * search hook, and — in future — the command palette without shipping the
 * component tree alongside it.
 */

import type { LucideIcon } from "lucide-react";
import { Code2, Folder, Receipt, Upload, Users } from "lucide-react";

interface ShortcutDef {
  keys: string[];
  desc: string;
}

export interface ShortcutGroup {
  id: string;
  label: string;
  icon: LucideIcon;
  iconClassName: string;
  shortcuts: ShortcutDef[];
}

export interface FeatureDef {
  id: string;
  icon: LucideIcon;
  color: string;
  title: string;
  href: string;
  summary: string;
  tips: string[];
}

export interface FaqDef {
  id: string;
  q: string;
  a: string;
}

export const FEATURES: readonly FeatureDef[] = [
  {
    id: "upload",
    icon: Upload,
    color: "text-blue-400 bg-blue-500/10 border-blue-500/20",
    title: "Upload",
    href: "/dashboard/upload",
    summary:
      "Import CSV, JSON, XLSX or TSV files. Auto-detects column types, checks data quality, and loads the data into DuckDB WASM for SQL queries.",
    tips: [
      "Drag & drop multiple files at once",
      "Use the Settings tab to force a specific delimiter",
      "DuckDB table name is derived from the filename",
      "Re-upload to restore a table after page refresh",
    ],
  },
  {
    id: "telecom-report",
    icon: Receipt,
    color: "text-amber-400 bg-amber-500/10 border-amber-500/20",
    title: "Telecom Report",
    href: "/dashboard/telecom-report",
    summary:
      "Purpose-built dashboard for DailyTransactions CSV reports. Generates KPIs by status and by channel (TTCASH, Voucher, Bill Payment, Data, Credit Transfer…).",
    tips: [
      "Expected file format: DailyTransactions_YYYYMMDD.csv (pipe-delimited)",
      "Upload the file in the Telecom Report page — not the generic Upload page",
      "KPIs only count transactions with status REUSSIE (PST, PST1…PST9)",
      "Use the date picker to filter a specific period",
    ],
  },
  {
    id: "collaborative",
    icon: Users,
    color: "text-rose-400 bg-rose-500/10 border-rose-500/20",
    title: "Collaborative",
    href: "/dashboard/collaborative",
    summary:
      "Leave comments on columns or datasets, track changes with team chat, and see live cursors from other open tabs.",
    tips: [
      "Uses Yjs CRDT — works offline-first, syncs when tabs reconnect",
      "Mention a colleague with @name in comments",
    ],
  },
  {
    id: "folders",
    icon: Folder,
    color: "text-yellow-400 bg-yellow-500/10 border-yellow-500/20",
    title: "Folders",
    href: "/dashboard/folders",
    summary:
      "Organise datasets into folders with tags and descriptions. Drag to reorder. Folders persist locally in IndexedDB and survive across sessions.",
    tips: ["Tag datasets for quick filtering in the global search"],
  },
] as const;

export const FAQS: readonly FaqDef[] = [
  {
    id: "faq-on-device",
    q: "Does any data leave my device?",
    a: "No external upload is required. Analytics run in the browser via DuckDB WASM, telecom files restore from IndexedDB, and local login uses a SQLite database on this machine.",
  },
  {
    id: "faq-refresh",
    q: "Will the Telecom Report survive a page refresh?",
    a: "Yes. The latest telecom source file, analytics cache, status mapping, layout, SQL history, and bookmarks are kept locally so the report can restore itself between sessions.",
  },
  {
    id: "faq-delimiters",
    q: "What delimiters are supported for the Telecom Report?",
    a: "The telecom report expects a pipe-delimited (|) CSV as generated by the billing system. If your file uses a different separator, pre-convert it before import.",
  },
  {
    id: "faq-max-size",
    q: "What is the maximum file size?",
    a: "Practical limit is around 500 MB in-browser. For larger files, split the file beforehand.",
  },
  {
    id: "faq-join",
    q: "How do I query two datasets together with a JOIN?",
    a: "Upload both files, then open the Browser (SQL IDE) page. Both tables are accessible by their DuckDB names. Example: SELECT a.*, b.name FROM table_a a JOIN table_b b ON a.id = b.id",
  },
  {
    id: "faq-shared-worker",
    q: "Why do I get a 'SharedWorker unavailable' message?",
    a: "The SharedWorker enables one DuckDB instance shared across all open tabs. It requires the worker to be built (run `pnpm run worker:build`). Without it, each tab gets its own DuckDB instance — everything still works, just tables won't be shared across tabs.",
  },
] as const;

export const SHORTCUT_GROUPS: readonly ShortcutGroup[] = [
  {
    id: "global",
    label: "Global shortcuts",
    icon: Code2,
    iconClassName: "text-indigo-400",
    shortcuts: [
      { keys: ["Ctrl", "K"], desc: "Open command palette" },
      { keys: ["Ctrl", "B"], desc: "Toggle sidebar" },
      { keys: ["Ctrl", "\\"], desc: "Toggle AI assistant" },
    ],
  },
  {
    id: "sql-ide",
    label: "SQL IDE shortcuts",
    icon: Code2,
    iconClassName: "text-emerald-400",
    shortcuts: [
      { keys: ["Ctrl", "Enter"], desc: "Run query" },
      { keys: ["Ctrl", "Shift", "F"], desc: "Format SQL" },
      { keys: ["Ctrl", "Z"], desc: "Undo" },
    ],
  },
] as const;
