import type { ColumnLineage, LEdge, LNode } from "./types";

// ─── Demo data ─────────────────────────────────────────────────────────────

export const DEMO_NODES: LNode[] = [
  {
    id: "raw_sales",
    name: "raw_sales",
    type: "source",
    subtype: "CSV Upload",
    status: "active",
    rowCount: 145230,
    colCount: 12,
    owner: "data-eng",
    description: "Raw sales transactions from ERP export",
    quality: 0.87,
    tags: ["sales", "raw", "erp"],
    lastUpdated: "2 min ago",
    upstreams: [],
    downstreams: ["clean_sales", "sales_staging"],
  },
  {
    id: "raw_customers",
    name: "raw_customers",
    type: "source",
    subtype: "API Sync",
    status: "active",
    rowCount: 48920,
    colCount: 18,
    owner: "data-eng",
    description: "Customer master data from CRM API",
    quality: 0.93,
    tags: ["customers", "raw", "crm"],
    lastUpdated: "15 min ago",
    upstreams: [],
    downstreams: ["clean_customers"],
  },
  {
    id: "raw_products",
    name: "raw_products",
    type: "source",
    subtype: "Database Sync",
    status: "active",
    rowCount: 2840,
    colCount: 8,
    owner: "product-team",
    description: "Product catalog from operational DB",
    quality: 0.99,
    tags: ["products", "raw"],
    lastUpdated: "1 hr ago",
    upstreams: [],
    downstreams: ["clean_products"],
  },
  {
    id: "sales_staging",
    name: "sales_staging",
    type: "transform",
    subtype: "DuckDB SQL",
    status: "active",
    rowCount: 143100,
    colCount: 12,
    owner: "data-eng",
    description: "Null removal, dedup, type casting",
    quality: 0.91,
    tags: ["staging", "sales"],
    lastUpdated: "2 min ago",
    duration: "3.2s",
    upstreams: ["raw_sales"],
    downstreams: ["clean_sales"],
  },
  {
    id: "clean_sales",
    name: "clean_sales",
    type: "transform",
    subtype: "DuckDB SQL",
    status: "active",
    rowCount: 141800,
    colCount: 14,
    owner: "analytics",
    description: "Validated, enriched, normalized sales data",
    quality: 0.96,
    tags: ["clean", "sales"],
    lastUpdated: "2 min ago",
    duration: "1.8s",
    upstreams: ["sales_staging", "raw_sales"],
    downstreams: ["sales_orders", "revenue_metrics"],
  },
  {
    id: "clean_customers",
    name: "clean_customers",
    type: "transform",
    subtype: "DuckDB SQL",
    status: "active",
    rowCount: 48100,
    colCount: 20,
    owner: "analytics",
    description: "Deduplicated, geocoded customer records",
    quality: 0.94,
    tags: ["clean", "customers"],
    lastUpdated: "18 min ago",
    duration: "2.1s",
    upstreams: ["raw_customers"],
    downstreams: ["sales_orders", "customer_segments"],
  },
  {
    id: "clean_products",
    name: "clean_products",
    type: "transform",
    subtype: "DuckDB SQL",
    status: "active",
    rowCount: 2801,
    colCount: 10,
    owner: "analytics",
    description: "Enriched product catalog with categories",
    quality: 0.99,
    tags: ["clean", "products"],
    lastUpdated: "1 hr ago",
    duration: "0.4s",
    upstreams: ["raw_products"],
    downstreams: ["sales_orders"],
  },
  {
    id: "sales_orders",
    name: "sales_orders",
    type: "model",
    subtype: "Mart Join",
    status: "active",
    rowCount: 139200,
    colCount: 28,
    owner: "analytics",
    description: "Joined sales + customers + products mart",
    quality: 0.95,
    tags: ["mart", "orders"],
    lastUpdated: "3 min ago",
    duration: "4.7s",
    upstreams: ["clean_sales", "clean_customers", "clean_products"],
    downstreams: ["revenue_metrics", "dept_summary", "country_report"],
  },
  {
    id: "customer_segments",
    name: "customer_segments",
    type: "model",
    subtype: "ML Clustering",
    status: "stale",
    rowCount: 48100,
    colCount: 6,
    owner: "ml-team",
    description: "RFM-based customer segments (stale — needs refresh)",
    quality: 0.78,
    tags: ["segments", "ml", "customers"],
    lastUpdated: "3 days ago",
    duration: "18.2s",
    upstreams: ["clean_customers"],
    downstreams: ["dept_summary"],
  },
  {
    id: "revenue_metrics",
    name: "revenue_metrics",
    type: "model",
    subtype: "Aggregation",
    status: "active",
    rowCount: 4380,
    colCount: 12,
    owner: "finance",
    description: "Daily/monthly revenue KPIs and trends",
    quality: 0.98,
    tags: ["metrics", "revenue", "finance"],
    lastUpdated: "5 min ago",
    duration: "0.9s",
    upstreams: ["clean_sales", "sales_orders"],
    downstreams: ["executive_dashboard"],
  },
  {
    id: "dept_summary",
    name: "dept_summary",
    type: "model",
    subtype: "Aggregation",
    status: "error",
    rowCount: 0,
    colCount: 8,
    owner: "analytics",
    description: "Department performance summary — FAILED: stale segment join",
    quality: 0,
    tags: ["summary", "department"],
    lastUpdated: "2 hrs ago",
    duration: "ERR",
    upstreams: ["sales_orders", "customer_segments"],
    downstreams: ["ops_dashboard"],
  },
  {
    id: "country_report",
    name: "country_report",
    type: "output",
    subtype: "Report Export",
    status: "active",
    rowCount: 182,
    colCount: 15,
    owner: "regional",
    description: "Country-level KPI report for regional teams",
    quality: 0.97,
    tags: ["report", "geo"],
    lastUpdated: "10 min ago",
    upstreams: ["sales_orders"],
    downstreams: [],
  },
  {
    id: "executive_dashboard",
    name: "executive_dashboard",
    type: "output",
    subtype: "BI Dashboard",
    status: "active",
    rowCount: 0,
    colCount: 0,
    owner: "exec",
    description: "C-suite revenue & growth dashboard",
    quality: 0.98,
    tags: ["dashboard", "exec"],
    lastUpdated: "6 min ago",
    upstreams: ["revenue_metrics"],
    downstreams: [],
  },
  {
    id: "ops_dashboard",
    name: "ops_dashboard",
    type: "output",
    subtype: "BI Dashboard",
    status: "error",
    rowCount: 0,
    colCount: 0,
    owner: "ops",
    description: "Operations dashboard — broken due to dept_summary failure",
    quality: 0,
    tags: ["dashboard", "ops"],
    lastUpdated: "2 hrs ago",
    upstreams: ["dept_summary"],
    downstreams: [],
  },
];

export const DEMO_EDGES: LEdge[] = [
  {
    id: "e1",
    source: "raw_sales",
    target: "sales_staging",
    type: "full",
    rowsTransferred: 145230,
  },
  {
    id: "e2",
    source: "raw_sales",
    target: "clean_sales",
    type: "partial",
    rowsTransferred: 145230,
  },
  {
    id: "e3",
    source: "raw_customers",
    target: "clean_customers",
    type: "full",
    rowsTransferred: 48920,
  },
  {
    id: "e4",
    source: "raw_products",
    target: "clean_products",
    type: "full",
    rowsTransferred: 2840,
  },
  {
    id: "e5",
    source: "sales_staging",
    target: "clean_sales",
    type: "full",
    rowsTransferred: 143100,
  },
  {
    id: "e6",
    source: "clean_sales",
    target: "sales_orders",
    type: "full",
    rowsTransferred: 141800,
  },
  {
    id: "e7",
    source: "clean_customers",
    target: "sales_orders",
    type: "full",
    rowsTransferred: 48100,
  },
  {
    id: "e8",
    source: "clean_products",
    target: "sales_orders",
    type: "full",
    rowsTransferred: 2801,
  },
  {
    id: "e9",
    source: "clean_customers",
    target: "customer_segments",
    type: "full",
    rowsTransferred: 48100,
  },
  {
    id: "e10",
    source: "clean_sales",
    target: "revenue_metrics",
    type: "full",
    rowsTransferred: 141800,
  },
  {
    id: "e11",
    source: "sales_orders",
    target: "revenue_metrics",
    type: "partial",
    rowsTransferred: 139200,
  },
  {
    id: "e12",
    source: "sales_orders",
    target: "dept_summary",
    type: "full",
    rowsTransferred: 139200,
  },
  {
    id: "e13",
    source: "customer_segments",
    target: "dept_summary",
    type: "full",
    rowsTransferred: 48100,
  },
  {
    id: "e14",
    source: "sales_orders",
    target: "country_report",
    type: "full",
    rowsTransferred: 139200,
  },
  {
    id: "e15",
    source: "revenue_metrics",
    target: "executive_dashboard",
    type: "full",
    rowsTransferred: 4380,
  },
  {
    id: "e16",
    source: "dept_summary",
    target: "ops_dashboard",
    type: "full",
    rowsTransferred: 0,
  },
];

export const DEMO_COL_LINEAGE: ColumnLineage[] = [
  {
    sourceNode: "raw_sales",
    sourceCol: "order_id",
    targetNode: "clean_sales",
    targetCol: "order_id",
  },
  {
    sourceNode: "raw_sales",
    sourceCol: "amount",
    targetNode: "clean_sales",
    targetCol: "revenue",
    transform: "CAST to DECIMAL",
  },
  {
    sourceNode: "raw_sales",
    sourceCol: "customer_id",
    targetNode: "sales_orders",
    targetCol: "customer_id",
  },
  {
    sourceNode: "raw_customers",
    sourceCol: "id",
    targetNode: "clean_customers",
    targetCol: "customer_id",
  },
  {
    sourceNode: "raw_customers",
    sourceCol: "first_name",
    targetNode: "clean_customers",
    targetCol: "full_name",
    transform: "CONCAT(first_name, ' ', last_name)",
  },
  {
    sourceNode: "clean_sales",
    sourceCol: "revenue",
    targetNode: "revenue_metrics",
    targetCol: "total_revenue",
    transform: "SUM()",
  },
  {
    sourceNode: "clean_sales",
    sourceCol: "revenue",
    targetNode: "revenue_metrics",
    targetCol: "avg_revenue",
    transform: "AVG()",
  },
  {
    sourceNode: "raw_products",
    sourceCol: "price",
    targetNode: "clean_products",
    targetCol: "unit_price",
    transform: "ROUND(price, 2)",
  },
];
