/**
 * Unit tests for src/features/agent-canvas/core/planner.ts
 *
 * Strategy:
 * - Mock the two IO boundaries: ai-bridge (aiReadySync + aiStructured) and plan-schema.
 * - Keep the real heuristicPlan / gridPos / buildUserPrompt / buildPlan logic live.
 * - Drive every branch: LLM path, heuristic fallback, LLM error → fallback.
 */

import { beforeEach, describe, expect, it, vi } from "vitest";

// ─── Boundary mocks (declared before importing target) ────────────────────────

const mockAiReadySync = vi.fn<() => boolean>(() => false);
const mockAiStructured = vi.fn<
  (
    system: string,
    user: string,
    schema: unknown,
    opts?: { maxTokens?: number },
  ) => Promise<unknown>
>();

vi.mock("@/features/agent-canvas/core/ai-bridge", () => ({
  aiReadySync: () => mockAiReadySync(),
  aiStructured: (
    system: string,
    user: string,
    schema: unknown,
    opts?: { maxTokens?: number },
  ) => mockAiStructured(system, user, schema, opts),
}));

// We do NOT mock plan-schema — we want the real Zod schemas to load.

import { buildPlan } from "@/features/agent-canvas/core/planner";
import type { DataSchema, DashboardPlan } from "@/features/agent-canvas/core/types";

// ─── Fixtures ─────────────────────────────────────────────────────────────────

function makeSchema(overrides: Partial<DataSchema> = {}): DataSchema {
  return {
    tableName: "tx_view",
    rowCount: 5000,
    columns: [
      {
        name: "region",
        duckType: "VARCHAR",
        semantic: "categorical",
        cardinality: 8,
        nullRate: 0.01,
        sample: ["north", "south"],
      },
      {
        name: "channel",
        duckType: "VARCHAR",
        semantic: "categorical",
        cardinality: 5,
        nullRate: 0,
        sample: ["web", "mobile"],
      },
      {
        name: "amount",
        duckType: "DOUBLE",
        semantic: "numeric",
        cardinality: 900,
        nullRate: 0,
        sample: ["1.0", "2.0"],
      },
      {
        name: "count",
        duckType: "INTEGER",
        semantic: "numeric",
        cardinality: 200,
        nullRate: 0.05,
        sample: ["10", "20"],
      },
      {
        name: "day",
        duckType: "DATE",
        semantic: "datetime",
        cardinality: 300,
        nullRate: 0,
        sample: ["2024-01-01"],
      },
    ],
    category: "telecom",
    summary: "Daily telecom transactions",
    dimensions: ["region", "channel"],
    metrics: ["amount", "count"],
    timeDims: ["day"],
    ...overrides,
  };
}

/** LLM response that satisfies DashboardPlanSchema */
function makeLLMPlan(): DashboardPlan & {
  widgets: Array<{
    id: string;
    title: string;
    chartType: string;
    sqlIntent: string;
    dimensions: string[];
    metrics: string[];
    reasoning: string;
  }>;
} {
  return {
    title: "LLM Dashboard",
    description: "Generated by LLM",
    widgets: [
      {
        id: "kpi-llm",
        title: "KPI Overview",
        chartType: "kpi-grid",
        sqlIntent: "Compute KPIs",
        dimensions: [],
        metrics: ["amount"],
        reasoning: "summary stats",
      },
      {
        id: "trend-llm",
        title: "Amount Over Time",
        chartType: "area",
        sqlIntent: "Group by day",
        dimensions: ["day"],
        metrics: ["amount"],
        reasoning: "temporal trend",
      },
      {
        id: "bar-llm",
        title: "By Channel",
        chartType: "bar",
        sqlIntent: "Group by channel",
        dimensions: ["channel"],
        metrics: ["amount"],
        reasoning: "channel breakdown",
      },
    ],
  };
}

beforeEach(() => {
  vi.clearAllMocks();
  mockAiReadySync.mockReturnValue(false);
});

// ─── Heuristic (fallback) planner tests ───────────────────────────────────────

describe("buildPlan — heuristic path (aiReadySync returns false)", () => {
  it("emits a 'No model warmed' message and a ready message via emit", async () => {
    // Arrange
    const schema = makeSchema();
    const emitted: string[] = [];

    // Act
    await buildPlan(schema, (t) => emitted.push(t));

    // Assert
    expect(emitted[0]).toContain("No model warmed");
    expect(emitted[1]).toContain("Rule-based plan ready");
  });

  it("returns a DashboardPlan with a non-empty widgets array", async () => {
    const schema = makeSchema();
    const plan = await buildPlan(schema, vi.fn());
    expect(plan.widgets.length).toBeGreaterThan(0);
  });

  it("includes a kpi-grid widget when metrics are present", async () => {
    const schema = makeSchema();
    const plan = await buildPlan(schema, vi.fn());
    const kpi = plan.widgets.find((w) => w.chartType === "kpi-grid");
    expect(kpi).toBeDefined();
    expect(kpi?.id).toBe("kpi-grid");
    expect(kpi?.title).toBe("Key Metrics Overview");
  });

  it("kpi-grid lists at most 5 metrics in the sqlIntent", async () => {
    // More than 5 metrics; heuristic slices to 5
    const schema = makeSchema({
      metrics: ["a", "b", "c", "d", "e", "f"],
    });
    const plan = await buildPlan(schema, vi.fn());
    const kpi = plan.widgets.find((w) => w.chartType === "kpi-grid");
    expect(kpi?.metrics).toHaveLength(5);
  });

  it("includes an area time-series widget when timeDims and metrics exist", async () => {
    const schema = makeSchema();
    const plan = await buildPlan(schema, vi.fn());
    const timeSeries = plan.widgets.find((w) => w.chartType === "area");
    expect(timeSeries).toBeDefined();
    expect(timeSeries?.dimensions).toContain("day");
    expect(timeSeries?.reasoning).toBe("Shows temporal trend");
  });

  it("omits the time-series widget when no timeDims are present", async () => {
    const schema = makeSchema({ timeDims: [] });
    const plan = await buildPlan(schema, vi.fn());
    const timeSeries = plan.widgets.find((w) => w.chartType === "area");
    expect(timeSeries).toBeUndefined();
  });

  it("chooses horizontal-bar when the first dimension name contains 'region'", async () => {
    const schema = makeSchema({ dimensions: ["region"] });
    const plan = await buildPlan(schema, vi.fn());
    const barWidget = plan.widgets.find(
      (w) => w.chartType === "horizontal-bar" || w.chartType === "bar",
    );
    expect(barWidget).toBeDefined();
    // 'region' dimension → horizontal-bar
    expect(barWidget?.chartType).toBe("horizontal-bar");
  });

  it("chooses horizontal-bar when rowCount < 20", async () => {
    const schema = makeSchema({ dimensions: ["channel"], rowCount: 10 });
    const plan = await buildPlan(schema, vi.fn());
    const barWidget = plan.widgets.find(
      (w) => w.chartType === "bar" || w.chartType === "horizontal-bar",
    );
    expect(barWidget?.chartType).toBe("horizontal-bar");
  });

  it("chooses bar (not horizontal-bar) for non-region dimension with rowCount >= 20", async () => {
    const schema = makeSchema({ dimensions: ["channel"], rowCount: 100 });
    const plan = await buildPlan(schema, vi.fn());
    const barWidget = plan.widgets.find(
      (w) => w.chartType === "bar" || w.chartType === "horizontal-bar",
    );
    expect(barWidget?.chartType).toBe("bar");
  });

  it("includes a donut widget for the second dimension when there are 2+ dimensions", async () => {
    const schema = makeSchema({ dimensions: ["region", "channel"] });
    const plan = await buildPlan(schema, vi.fn());
    const donut = plan.widgets.find((w) => w.chartType === "donut" && w.id === "pie-second-dim");
    expect(donut).toBeDefined();
    expect(donut?.dimensions).toContain("channel");
  });

  it("omits pie-second-dim when there is only 1 dimension", async () => {
    const schema = makeSchema({ dimensions: ["channel"] });
    const plan = await buildPlan(schema, vi.fn());
    const donut = plan.widgets.find((w) => w.id === "pie-second-dim");
    expect(donut).toBeUndefined();
  });

  it("adds a status-breakdown donut for telecom category", async () => {
    const schema = makeSchema({ category: "telecom" });
    const plan = await buildPlan(schema, vi.fn());
    const status = plan.widgets.find((w) => w.id === "status-breakdown");
    expect(status).toBeDefined();
    expect(status?.chartType).toBe("donut");
  });

  it("omits status-breakdown for non-telecom category", async () => {
    const schema = makeSchema({ category: "retail" });
    const plan = await buildPlan(schema, vi.fn());
    const status = plan.widgets.find((w) => w.id === "status-breakdown");
    expect(status).toBeUndefined();
  });

  it("adds a funnel widget for ecommerce category", async () => {
    const schema = makeSchema({ category: "ecommerce" });
    const plan = await buildPlan(schema, vi.fn());
    const funnel = plan.widgets.find((w) => w.id === "funnel");
    expect(funnel).toBeDefined();
    expect(funnel?.chartType).toBe("funnel");
  });

  it("omits funnel for non-ecommerce category", async () => {
    const schema = makeSchema({ category: "telecom" });
    const plan = await buildPlan(schema, vi.fn());
    const funnel = plan.widgets.find((w) => w.id === "funnel");
    expect(funnel).toBeUndefined();
  });

  it("includes a scatter widget when there are 2+ metrics", async () => {
    const schema = makeSchema({ metrics: ["amount", "count"] });
    const plan = await buildPlan(schema, vi.fn());
    const scatter = plan.widgets.find((w) => w.chartType === "scatter");
    expect(scatter).toBeDefined();
    expect(scatter?.metrics).toHaveLength(2);
  });

  it("omits scatter when there is only 1 metric", async () => {
    const schema = makeSchema({ metrics: ["amount"] });
    const plan = await buildPlan(schema, vi.fn());
    const scatter = plan.widgets.find((w) => w.chartType === "scatter");
    expect(scatter).toBeUndefined();
  });

  it("includes a stacked-bar widget when there are 2+ dimensions and 1+ metrics", async () => {
    const schema = makeSchema({ dimensions: ["region", "channel"], metrics: ["amount"] });
    const plan = await buildPlan(schema, vi.fn());
    const stacked = plan.widgets.find((w) => w.chartType === "stacked-bar");
    expect(stacked).toBeDefined();
    expect(stacked?.dimensions).toHaveLength(2);
  });

  it("omits stacked-bar when there is only 1 dimension", async () => {
    const schema = makeSchema({ dimensions: ["channel"], metrics: ["amount"] });
    const plan = await buildPlan(schema, vi.fn());
    const stacked = plan.widgets.find((w) => w.chartType === "stacked-bar");
    expect(stacked).toBeUndefined();
  });

  it("always includes a data-table widget", async () => {
    const schema = makeSchema();
    const plan = await buildPlan(schema, vi.fn());
    const table = plan.widgets.find((w) => w.chartType === "data-table");
    expect(table).toBeDefined();
    expect(table?.id).toBe("data-table");
  });

  it("returns no kpi-grid when there are no metrics", async () => {
    const schema = makeSchema({ metrics: [] });
    const plan = await buildPlan(schema, vi.fn());
    const kpi = plan.widgets.find((w) => w.chartType === "kpi-grid");
    expect(kpi).toBeUndefined();
  });

  it("capitalizes category in the dashboard title", async () => {
    const schema = makeSchema({ category: "telecom" });
    const plan = await buildPlan(schema, vi.fn());
    expect(plan.title).toBe("Telecom Dashboard");
  });

  it("sets the plan description to schema.summary", async () => {
    const schema = makeSchema({ summary: "My special summary" });
    const plan = await buildPlan(schema, vi.fn());
    expect(plan.description).toBe("My special summary");
  });

  it("emits the correct widget count in the ready message", async () => {
    const schema = makeSchema();
    const emitted: string[] = [];
    const plan = await buildPlan(schema, (t) => emitted.push(t));
    const readyMsg = emitted.find((m) => m.includes("Rule-based plan ready"));
    expect(readyMsg).toContain(`${plan.widgets.length} widgets`);
  });

  it("works with a completely empty schema (no dims, metrics, timeDims)", async () => {
    // Use a neutral category so no category-specific extras are added
    const schema = makeSchema({ dimensions: [], metrics: [], timeDims: [], category: "retail" });
    const plan = await buildPlan(schema, vi.fn());
    // Only data-table should be present (no kpi, no time series, no bar, etc.)
    expect(plan.widgets).toHaveLength(1);
    expect(plan.widgets[0].chartType).toBe("data-table");
  });
});

// ─── Grid position logic ───────────────────────────────────────────────────────

describe("buildPlan — grid positions (via heuristic plan)", () => {
  it("assigns x=0 and full width (w=12) to wide chart types (stacked-bar)", async () => {
    const schema = makeSchema({ dimensions: ["region", "channel"], metrics: ["amount"] });
    const plan = await buildPlan(schema, vi.fn());
    const stacked = plan.widgets.find((w) => w.chartType === "stacked-bar");
    expect(stacked?.position.w).toBe(12);
    expect(stacked?.position.x).toBe(0);
  });

  it("assigns w=12 to data-table (wide)", async () => {
    const schema = makeSchema();
    const plan = await buildPlan(schema, vi.fn());
    const table = plan.widgets.find((w) => w.chartType === "data-table");
    expect(table?.position.w).toBe(12);
  });

  it("assigns w=6 to non-wide charts (bar)", async () => {
    const schema = makeSchema({ dimensions: ["channel"], metrics: ["amount"] });
    const plan = await buildPlan(schema, vi.fn());
    const bar = plan.widgets.find((w) => w.chartType === "bar" || w.chartType === "horizontal-bar");
    expect(bar?.position.w).toBe(6);
  });

  it("assigns h=5 to tall chart types (scatter)", async () => {
    const schema = makeSchema({ metrics: ["amount", "count"] });
    const plan = await buildPlan(schema, vi.fn());
    const scatter = plan.widgets.find((w) => w.chartType === "scatter");
    expect(scatter?.position.h).toBe(5);
  });

  it("assigns h=3 to kpi-grid", async () => {
    const schema = makeSchema();
    const plan = await buildPlan(schema, vi.fn());
    const kpi = plan.widgets.find((w) => w.chartType === "kpi-grid");
    expect(kpi?.position.h).toBe(3);
  });

  it("assigns h=4 to regular charts (area)", async () => {
    const schema = makeSchema();
    const plan = await buildPlan(schema, vi.fn());
    const area = plan.widgets.find((w) => w.chartType === "area");
    expect(area?.position.h).toBe(4);
  });

  it("positions non-wide charts in two columns (x=0 or x=6)", async () => {
    const schema = makeSchema({
      dimensions: ["region", "channel"],
      metrics: ["amount", "count"],
      timeDims: [],
      category: "retail",
    });
    const plan = await buildPlan(schema, vi.fn());
    const nonWide = plan.widgets.filter((w) => w.position.w === 6);
    for (const w of nonWide) {
      expect([0, 6]).toContain(w.position.x);
    }
  });
});

// ─── LLM path ─────────────────────────────────────────────────────────────────

describe("buildPlan — LLM path (aiReadySync returns true)", () => {
  beforeEach(() => {
    mockAiReadySync.mockReturnValue(true);
  });

  it("calls aiStructured with SYSTEM_PROMPT and a user prompt", async () => {
    mockAiStructured.mockResolvedValue(makeLLMPlan());
    const schema = makeSchema();
    await buildPlan(schema, vi.fn());
    expect(mockAiStructured).toHaveBeenCalledTimes(1);
    const [system, user] = mockAiStructured.mock.calls[0];
    expect(system).toContain("expert data visualization engineer");
    expect(user).toContain(schema.summary);
    expect(user).toContain(schema.category);
  });

  it("passes maxTokens: 1800 to aiStructured", async () => {
    mockAiStructured.mockResolvedValue(makeLLMPlan());
    const schema = makeSchema();
    await buildPlan(schema, vi.fn());
    const opts = mockAiStructured.mock.calls[0][3];
    expect((opts as { maxTokens?: number })?.maxTokens).toBe(1800);
  });

  it("emits an 'Asking the LLM planner' message at the start", async () => {
    mockAiStructured.mockResolvedValue(makeLLMPlan());
    const emitted: string[] = [];
    await buildPlan(makeSchema(), (t) => emitted.push(t));
    expect(emitted[0]).toContain("Asking the LLM planner");
  });

  it("emits an 'LLM plan ready' message including widget count and title", async () => {
    mockAiStructured.mockResolvedValue(makeLLMPlan());
    const emitted: string[] = [];
    await buildPlan(makeSchema(), (t) => emitted.push(t));
    const readyMsg = emitted.find((m) => m.includes("LLM plan ready"));
    expect(readyMsg).toContain("3 widgets");
    expect(readyMsg).toContain("LLM Dashboard");
  });

  it("returns a plan with title and description from the LLM response", async () => {
    mockAiStructured.mockResolvedValue(makeLLMPlan());
    const plan = await buildPlan(makeSchema(), vi.fn());
    expect(plan.title).toBe("LLM Dashboard");
    expect(plan.description).toBe("Generated by LLM");
  });

  it("assigns deterministic grid positions to LLM widgets", async () => {
    mockAiStructured.mockResolvedValue(makeLLMPlan());
    const plan = await buildPlan(makeSchema(), vi.fn());
    for (const w of plan.widgets) {
      expect(w.position).toBeDefined();
      expect(typeof w.position.x).toBe("number");
      expect(typeof w.position.y).toBe("number");
      expect(typeof w.position.w).toBe("number");
      expect(typeof w.position.h).toBe("number");
    }
  });

  it("falls back to 'w<i>' id when LLM widget id is empty", async () => {
    const llmPlan = makeLLMPlan();
    // Corrupt the id on the first widget
    (llmPlan.widgets[0] as { id: string }).id = "";
    mockAiStructured.mockResolvedValue(llmPlan);
    const plan = await buildPlan(makeSchema(), vi.fn());
    expect(plan.widgets[0].id).toBe("w0");
  });

  it("falls back to 'Chart <i+1>' title when LLM widget title is empty", async () => {
    const llmPlan = makeLLMPlan();
    (llmPlan.widgets[1] as { title: string }).title = "";
    mockAiStructured.mockResolvedValue(llmPlan);
    const plan = await buildPlan(makeSchema(), vi.fn());
    expect(plan.widgets[1].title).toBe("Chart 2");
  });

  it("falls back to schema.summary as description when LLM description is missing", async () => {
    const llmPlan = makeLLMPlan();
    (llmPlan as { description: string }).description = "";
    mockAiStructured.mockResolvedValue(llmPlan);
    const schema = makeSchema({ summary: "Custom summary" });
    const plan = await buildPlan(schema, vi.fn());
    expect(plan.description).toBe("Custom summary");
  });

  it("falls back to 'Dashboard' title when LLM title is empty", async () => {
    const llmPlan = makeLLMPlan();
    (llmPlan as { title: string }).title = "";
    mockAiStructured.mockResolvedValue(llmPlan);
    const plan = await buildPlan(makeSchema(), vi.fn());
    expect(plan.title).toBe("Dashboard");
  });

  it("falls back to schema sqlIntent default when LLM sqlIntent is missing", async () => {
    const llmPlan = makeLLMPlan();
    (llmPlan.widgets[0] as { sqlIntent: string }).sqlIntent = "";
    mockAiStructured.mockResolvedValue(llmPlan);
    const schema = makeSchema();
    const plan = await buildPlan(schema, vi.fn());
    expect(plan.widgets[0].sqlIntent).toContain(schema.tableName);
  });

  it("attaches reasoning from LLM to widget", async () => {
    mockAiStructured.mockResolvedValue(makeLLMPlan());
    const plan = await buildPlan(makeSchema(), vi.fn());
    expect(plan.widgets[0].reasoning).toBe("summary stats");
  });

  it("populates empty dimensions/metrics arrays when LLM omits them", async () => {
    const llmPlan = makeLLMPlan();
    // Simulate nullish fields (undefined comes through nullish coalescing)
    delete (llmPlan.widgets[0] as Partial<(typeof llmPlan.widgets)[0]>).dimensions;
    delete (llmPlan.widgets[0] as Partial<(typeof llmPlan.widgets)[0]>).metrics;
    mockAiStructured.mockResolvedValue(llmPlan);
    const plan = await buildPlan(makeSchema(), vi.fn());
    expect(plan.widgets[0].dimensions).toEqual([]);
    expect(plan.widgets[0].metrics).toEqual([]);
  });
});

// ─── LLM error → heuristic fallback ───────────────────────────────────────────

describe("buildPlan — LLM error falls back to heuristics", () => {
  beforeEach(() => {
    mockAiReadySync.mockReturnValue(true);
  });

  it("falls back to heuristic plan when aiStructured throws", async () => {
    mockAiStructured.mockRejectedValue(new Error("model overloaded"));
    const schema = makeSchema();
    const plan = await buildPlan(schema, vi.fn());
    // Heuristic plan always includes a data-table
    const table = plan.widgets.find((w) => w.chartType === "data-table");
    expect(table).toBeDefined();
  });

  it("emits an error message mentioning the thrown error", async () => {
    mockAiStructured.mockRejectedValue(new Error("network timeout"));
    const emitted: string[] = [];
    await buildPlan(makeSchema(), (t) => emitted.push(t));
    const errMsg = emitted.find((m) => m.includes("LLM planner failed"));
    expect(errMsg).toContain("network timeout");
  });

  it("emits a 'Fallback plan' ready message after failure", async () => {
    mockAiStructured.mockRejectedValue(new Error("crash"));
    const emitted: string[] = [];
    const plan = await buildPlan(makeSchema(), (t) => emitted.push(t));
    const fallbackMsg = emitted.find((m) => m.includes("Fallback plan"));
    expect(fallbackMsg).toContain(`${plan.widgets.length} widgets`);
  });

  it("returns the same heuristic plan structure as the no-AI path on failure", async () => {
    mockAiStructured.mockRejectedValue(new Error("fail"));
    const schema = makeSchema();

    // Disable AI for comparison
    mockAiReadySync.mockReturnValue(false);
    const heuristicPlan = await buildPlan(schema, vi.fn());

    // Re-enable AI (will fail → fallback)
    mockAiReadySync.mockReturnValue(true);
    mockAiStructured.mockRejectedValue(new Error("fail"));
    const fallbackPlan = await buildPlan(schema, vi.fn());

    // Both plans should have the same widget ids in the same order
    const heuristicIds = heuristicPlan.widgets.map((w) => w.id);
    const fallbackIds = fallbackPlan.widgets.map((w) => w.id);
    expect(fallbackIds).toEqual(heuristicIds);
  });
});

// ─── User prompt construction ─────────────────────────────────────────────────

describe("buildPlan — user prompt content (via LLM path mock calls)", () => {
  beforeEach(() => {
    mockAiReadySync.mockReturnValue(true);
    mockAiStructured.mockResolvedValue(makeLLMPlan());
  });

  it("includes column name, semantic, cardinality, and nullRate in the user prompt", async () => {
    const schema = makeSchema();
    await buildPlan(schema, vi.fn());
    const user = mockAiStructured.mock.calls[0][1] as string;
    // Column summaries are encoded as name:semantic(cardinality=...,nullRate=...)
    expect(user).toContain("region:categorical");
    expect(user).toContain("cardinality=8");
    expect(user).toContain("nullRate=1%");
  });

  it("includes dimensions and metrics lists in the user prompt", async () => {
    const schema = makeSchema();
    await buildPlan(schema, vi.fn());
    const user = mockAiStructured.mock.calls[0][1] as string;
    expect(user).toContain("region");
    expect(user).toContain("amount");
  });

  it("includes row count in the user prompt", async () => {
    const schema = makeSchema({ rowCount: 42000 });
    await buildPlan(schema, vi.fn());
    const user = mockAiStructured.mock.calls[0][1] as string;
    // Row count is locale-formatted
    expect(user).toContain("42");
  });

  it("shows 'none' for temporal columns when timeDims is empty", async () => {
    const schema = makeSchema({ timeDims: [] });
    await buildPlan(schema, vi.fn());
    const user = mockAiStructured.mock.calls[0][1] as string;
    expect(user).toContain("Temporal columns: none");
  });

  it("shows 'none' for dimensions when dimensions is empty", async () => {
    const schema = makeSchema({ dimensions: [] });
    await buildPlan(schema, vi.fn());
    const user = mockAiStructured.mock.calls[0][1] as string;
    expect(user).toContain("Good GROUP-BY dimensions: none");
  });

  it("shows 'none' for metrics when metrics is empty", async () => {
    const schema = makeSchema({ metrics: [] });
    await buildPlan(schema, vi.fn());
    const user = mockAiStructured.mock.calls[0][1] as string;
    expect(user).toContain("Good aggregation metrics: none");
  });
});
