import type { Capability } from "./types";

export const CAPABILITIES: Capability[] = [
  {
    id: "telecom.identifyTable",
    label: "Identify active telecom table",
    area: "telecom",
    requires: ["DuckDB"],
    produces: ["DatasetLane.activeTable", "DatasetLane.columns"],
    runtime: "duckdb-worker",
    cost: "instant",
    offline: true,
    cacheable: false,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.validateMapping",
    label: "Validate telecom mapping",
    area: "telecom",
    requires: ["DatasetLane.columns", "ColumnMapping"],
    produces: ["TelecomLane.mappingIssues"],
    runtime: "main",
    cost: "instant",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.buildSemanticModel",
    label: "Build telecom semantic model",
    area: "telecom",
    requires: ["DatasetLane.activeTable", "ColumnMapping"],
    produces: ["TelecomSemanticModel"],
    runtime: "main",
    cost: "instant",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.overviewKpis",
    label: "Compute overview KPIs",
    area: "telecom",
    requires: ["DatasetLane.activeTable", "TelecomSemanticModel"],
    produces: ["KPISummary", "Evidence"],
    runtime: "duckdb-worker",
    cost: "fast",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.successRateTrend",
    label: "Analyze success-rate trend",
    area: "telecom",
    requires: ["DatasetLane.activeTable", "TelecomSemanticModel"],
    produces: ["DailyTrendRow", "Evidence"],
    runtime: "duckdb-worker",
    cost: "fast",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.periodCompare",
    label: "Compare latest period to baseline",
    area: "telecom",
    requires: ["DailyTrendRow"],
    produces: ["PeriodKPI", "Evidence"],
    runtime: "duckdb-worker",
    cost: "fast",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.canalCompare",
    label: "Compare canals",
    area: "telecom",
    requires: ["RawCanalRow"],
    produces: ["Evidence"],
    runtime: "main",
    cost: "instant",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.failureByStatus",
    label: "Break down status mix",
    area: "telecom",
    requires: ["StatusRow"],
    produces: ["Evidence"],
    runtime: "main",
    cost: "instant",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.failureBySubStatus",
    label: "Break down sub-status failures",
    area: "telecom",
    requires: ["DatasetLane.activeTable", "TelecomSemanticModel"],
    produces: ["SubStatusRow", "Evidence"],
    runtime: "duckdb-worker",
    cost: "fast",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.anomalyRadar",
    label: "Run anomaly radar",
    area: "telecom",
    requires: ["DatasetLane.activeTable", "DailyTrendRow"],
    produces: ["RowAnomaly", "Evidence"],
    runtime: "duckdb-worker",
    cost: "deep",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.userConcentration",
    label: "Find user concentration risk",
    area: "telecom",
    requires: ["DatasetLane.activeTable", "DailyTrendRow"],
    produces: ["TopAccountRow", "Evidence"],
    runtime: "duckdb-worker",
    cost: "fast",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "evidence.validate",
    label: "Validate evidence",
    area: "governance",
    requires: ["Evidence"],
    produces: ["DecisionLane"],
    runtime: "main",
    cost: "instant",
    offline: true,
    cacheable: false,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "report.briefFromEvidence",
    label: "Draft analyst brief",
    area: "output",
    requires: ["EvidenceLane.acceptedIds"],
    produces: ["DecisionLane"],
    runtime: "main",
    cost: "instant",
    offline: true,
    cacheable: false,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.hourlyPattern",
    label: "Hourly traffic pattern",
    area: "telecom",
    requires: ["DatasetLane.activeTable", "TelecomSemanticModel"],
    produces: ["HourlyRow", "Evidence"],
    runtime: "duckdb-worker",
    cost: "fast",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.amountBandAnalysis",
    label: "Amount band distribution",
    area: "telecom",
    requires: ["DatasetLane.activeTable", "TelecomSemanticModel"],
    produces: ["Evidence"],
    runtime: "duckdb-worker",
    cost: "fast",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.dataQualityProfile",
    label: "Data quality profile",
    area: "analysis",
    requires: ["DatasetLane.activeTable", "TelecomSemanticModel"],
    produces: ["Evidence"],
    runtime: "duckdb-worker",
    cost: "fast",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
  {
    id: "telecom.inferMapping",
    label: "Infer column mapping",
    area: "telecom",
    requires: ["DatasetLane.columns"],
    produces: ["TelecomLane.mapping"],
    runtime: "main",
    cost: "instant",
    offline: true,
    cacheable: true,
    deterministic: true,
    approvalRequired: false,
  },
];
